[flyway]
locations = ["filesystem:migrations"]

[environments.default]
locations = ["filesystem:migrations"]
url = "jdbc:mysql://localhost:3306/flywaydemo"
user = "yorman-dev"
password = "devP4ssw0rd*"